---
- name: debian | Installing Debian Pre-Req Packages
  apt:
    name: "{{ observium_debian_pre_reqs }}"
    state: "present"

- name: debian | Installing LibVirt Packages to monitor (If Desired)
  apt:
    name: "{{ libvirt-bin }}"
    state: "present"
  when: observium_monitor_libvirt_vms
