---
# tasks file for ansible-observium
- include_tasks: set_facts.yml

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: install.yml
  when: not observium_commercial

- include_tasks: install-commercial.yml
  when: observium_commercial

- include_tasks: config.yml

- include_tasks: users.yml

- include_tasks: cron.yml
